version: '3.7'

services:
  web:
    container_name: flowerShopApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 7000:7000
    links:
      - db
  db:
    container_name: postgres
    image: postgres:12.1
    ports:
      - 5432:5432